# Generated by Django 2.2.5 on 2019-10-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191002_0708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='iage',
            new_name='image',
        ),
    ]
